version: "3.7"
services:
  api-service:
    build: "./api"
    ports: 
      - "5000:5000"
    env_file: 
      - ./api/.env
    environment: 
      - DB_CONNECTION_STRING=mongodb://db-service/milou-project
    depends_on: 
      - db-service
  client:
    build: "./client"
    ports:
      - "8080:8080"
    depends_on: 
      - api-service
  db-service:
    image: mongo:latest
    ports: 
      - "27018:27018"